In [1]:
import pandas as pd

In [8]:
df =  pd.read_csv("data/main/dataset.csv")

In [9]:
df

,Unnamed: 0,repo_name,num_contributors,total_contributions,top1_contribution_share,top5_contribution_share,contribution_gini,median_contributions,num_deployments,has_deployments,...,contributors_to_stars_ratio,tag_release_velocity,interaction_ratio,development_ratio,external_interest_event_ratio,stars_per_size,forks_per_size,issues_per_size,error,label
0,0,feast-dev/feast,30.0,3139.0,0.173941,0.475948,0.475385,61.5,30.0,1.0,...,0.004283,0.011096,0.100000,0.466667,0.266667,0.027528,0.005168,0.001360,NaN,1
1,1,tmux/tmux,19.0,9800.0,0.802143,0.997551,0.923963,2.0,0.0,0.0,...,0.000421,0.007521,0.500000,0.066667,0.366667,2.358165,0.135984,0.002873,NaN,1
2,2,ultralytics/ultralytics,30.0,3551.0,0.443537,0.813292,0.779283,21.5,30.0,1.0,...,0.000525,0.022346,0.333333,0.366667,0.233333,1.037995,0.199797,0.005900,NaN,1
3,3,denoland/fresh,30.0,1396.0,0.474928,0.803009,0.767240,8.5,30.0,1.0,...,0.002181,0.016352,0.333333,0.366667,0.133333,0.300949,0.016385,0.001794,NaN,1
4,4,milvus-io/milvus,30.0,17783.0,0.096947,0.307372,0.252978,506.5,0.0,0.0,...,0.000677,0.012326,0.500000,0.466667,0.033333,0.151276,0.013655,0.003018,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,406,Solido/awesome-flutter,30.0,473.0,0.689218,0.773784,0.715927,4.0,30.0,1.0,...,0.000500,0.000000,0.000000,0.033333,0.966667,16.931151,1.939334,0.006772,NaN,0
407,407,fabricjs/fabric.js,30.0,4830.0,0.414079,0.908075,0.842636,18.5,30.0,1.0,...,0.000963,0.005155,0.233333,0.033333,0.733333,0.125760,0.014633,0.001893,NaN,0
408,408,octocat/Hello-World,3.0,3.0,0.333333,1.000000,0.000000,1.0,0.0,0.0,...,0.000839,0.000000,0.166667,0.000000,0.800000,3575.000000,6157.000000,5863.000000,NaN,0
409,409,docker/getting-started,30.0,166.0,0.421687,0.819277,0.744980,1.0,0.0,0.0,...,0.009794,0.000000,0.142857,0.000000,0.821429,0.571669,1.191863,0.020903,NaN,0
410,410,facebookarchive/rebound,10.0,119.0,0.899160,0.957983,0.814286,1.0,0.0,0.0,...,0.001853,0.002174,0.000000,0.000000,0.000000,0.228464,0.033823,0.001312,NaN,0

In [10]:
df.drop(columns=["Unnamed: 0", "repo_name"], inplace=True)

In [11]:
df

,num_contributors,total_contributions,top1_contribution_share,top5_contribution_share,contribution_gini,median_contributions,num_deployments,has_deployments,num_unique_refs,tag_based_deployment_ratio,...,contributors_to_stars_ratio,tag_release_velocity,interaction_ratio,development_ratio,external_interest_event_ratio,stars_per_size,forks_per_size,issues_per_size,error,label
0,30.0,3139.0,0.173941,0.475948,0.475385,61.5,30.0,1.0,2.0,0.0,...,0.004283,0.011096,0.100000,0.466667,0.266667,0.027528,0.005168,0.001360,NaN,1
1,19.0,9800.0,0.802143,0.997551,0.923963,2.0,0.0,0.0,0.0,0.0,...,0.000421,0.007521,0.500000,0.066667,0.366667,2.358165,0.135984,0.002873,NaN,1
2,30.0,3551.0,0.443537,0.813292,0.779283,21.5,30.0,1.0,1.0,0.0,...,0.000525,0.022346,0.333333,0.366667,0.233333,1.037995,0.199797,0.005900,NaN,1
3,30.0,1396.0,0.474928,0.803009,0.767240,8.5,30.0,1.0,30.0,0.0,...,0.002181,0.016352,0.333333,0.366667,0.133333,0.300949,0.016385,0.001794,NaN,1
4,30.0,17783.0,0.096947,0.307372,0.252978,506.5,0.0,0.0,0.0,0.0,...,0.000677,0.012326,0.500000,0.466667,0.033333,0.151276,0.013655,0.003018,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,30.0,473.0,0.689218,0.773784,0.715927,4.0,30.0,1.0,1.0,0.0,...,0.000500,0.000000,0.000000,0.033333,0.966667,16.931151,1.939334,0.006772,NaN,0
407,30.0,4830.0,0.414079,0.908075,0.842636,18.5,30.0,1.0,8.0,0.0,...,0.000963,0.005155,0.233333,0.033333,0.733333,0.125760,0.014633,0.001893,NaN,0
408,3.0,3.0,0.333333,1.000000,0.000000,1.0,0.0,0.0,0.0,0.0,...,0.000839,0.000000,0.166667,0.000000,0.800000,3575.000000,6157.000000,5863.000000,NaN,0
409,30.0,166.0,0.421687,0.819277,0.744980,1.0,0.0,0.0,0.0,0.0,...,0.009794,0.000000,0.142857,0.000000,0.821429,0.571669,1.191863,0.020903,NaN,0
410,10.0,119.0,0.899160,0.957983,0.814286,1.0,0.0,0.0,0.0,0.0,...,0.001853,0.002174,0.000000,0.000000,0.000000,0.228464,0.033823,0.001312,NaN,0

In [12]:
df.columns

Index(['num_contributors', 'total_contributions', 'top1_contribution_share',
       'top5_contribution_share', 'contribution_gini', 'median_contributions',
       'num_deployments', 'has_deployments', 'num_unique_refs',
       'tag_based_deployment_ratio', 'deployment_recency_days', 'num_events',
       'num_unique_event_types', 'dominant_event_type', 'dominant_event_ratio',
       'event_type_entropy', 'has_IssuesEvent', 'has_PullRequestEvent',
       'has_IssueCommentEvent', 'recent_event_density', 'IssuesEvent_ratio',
       'IssueCommentEvent_ratio', 'PullRequestEvent_ratio', 'PushEvent_ratio',
       'WatchEvent_ratio', 'ForkEvent_ratio', 'stargazers_count',
       'subscribers_count', 'subscribers_to_stars_ratio',
       'primary_language_ratio', 'top2_ratio', 'top3_ratio',
       'language_entropy', 'minor_lang_ratio', 'infra_ratio', 'markup_ratio',
       'is_monolingual', 'compiled_ratio', 'num_tags', 'stable_tag_ratio',
       'prerelease_tag_ratio', 'latest_tag_is_stable',
       'latest_tag_is_prerelease', 'semver_tag_ratio', 'num_major_versions',
       'num_minor_versions', 'repo_age_days', 'last_update_recency_days',
       'last_push_recency_days', 'update_push_gap_days', 'repo_size',
       'forks_count', 'open_issues_count', 'network_count', 'has_issues',
       'has_projects', 'has_downloads', 'has_wiki', 'has_pages',
       'has_discussions', 'archived', 'disabled', 'allow_forking',
       'has_pull_requests', 'forks_to_stars_ratio',
       'open_issues_to_stars_ratio', 'stars_per_repo_age_day',
       'forks_per_repo_age_day', 'top1_contribution_ratio',
       'top3_contribution_ratio', 'contribution_entropy',
       'contributors_to_stars_ratio', 'tag_release_velocity',
       'interaction_ratio', 'development_ratio',
       'external_interest_event_ratio', 'stars_per_size', 'forks_per_size',
       'issues_per_size', 'error', 'label'],
      dtype='str')

---

# **Feature Engineering**

## **1. contributor_features**

**의미**

“누가 얼마나 다양하게 유지보수하는가”

**핵심 질문**

- 소수 maintainer 의존도가 높은가?
- contributor 생태계가 건강한가?
- bus factor 위험이 있는가?

In [13]:
contributor_features = [
    "num_contributors",
    "total_contributions",
    "top1_contribution_share",
    "top5_contribution_share",
    "contribution_gini",
    "median_contributions",
    "top1_contribution_ratio",
    "top3_contribution_ratio",
    "contribution_entropy",
    "contributors_to_stars_ratio",
]

## **2. Deployment / Release Maturity**

**의미**

“실제로 운영·배포되는 OSS인가”

**핵심 질문**
- release 체계가 안정적인가?
- semantic versioning 잘 지키는가?
- deployment 활동이 존재하는가?

In [14]:
release_features = [
    "num_deployments",
    "has_deployments",
    "num_unique_refs",
    "tag_based_deployment_ratio",
    "deployment_recency_days",
    "num_tags",
    "stable_tag_ratio",
    "prerelease_tag_ratio",
    "latest_tag_is_stable",
    "latest_tag_is_prerelease",
    "semver_tag_ratio",
    "num_major_versions",
    "num_minor_versions",
    "tag_release_velocity",
]

## **3. Activity / Event Dynamics**

**의미**

“프로젝트가 실제로 살아 움직이는가”

**핵심 질문**
- interaction 활발한가?
- 개발 이벤트 중심인가?
- 단순 인기 repo인가?

In [15]:
event_features = [
    "num_events",
    "num_unique_event_types",
    "dominant_event_ratio",
    "event_type_entropy",
    "has_IssuesEvent",
    "has_PullRequestEvent",
    "has_IssueCommentEvent",
    "recent_event_density",
    "IssuesEvent_ratio",
    "IssueCommentEvent_ratio",
    "PullRequestEvent_ratio",
    "PushEvent_ratio",
    "WatchEvent_ratio",
    "ForkEvent_ratio",
    "interaction_ratio",
    "development_ratio",
    "external_interest_event_ratio",
]

## **4. Popularity / Ecosystem Interest**

**의미**

“얼마나 주목받는가”

**핵심 질문**
- popularity와 health는 같은가?
- star inflation 존재하는가?

In [16]:
popularity_features = [
    "stargazers_count",
    "subscribers_count",
    "subscribers_to_stars_ratio",
    "forks_count",
    "network_count",
    "forks_to_stars_ratio",
    "open_issues_to_stars_ratio",
    "stars_per_repo_age_day",
    "forks_per_repo_age_day",
    "stars_per_size",
    "forks_per_size",
]

## **5. Language / Architectural Diversity**

**의미**

“프로젝트 구조 복잡성과 기술 다양성”

**핵심 질문**
- 단일 언어 vs multi-language
- infra/system repo 특성 존재?
- architecture complexity 차이?

In [18]:
language_features = [
    "primary_language_ratio",
    "top2_ratio",
    "top3_ratio",
    "language_entropy",
    "minor_lang_ratio",
    "infra_ratio",
    "markup_ratio",
    "is_monolingual",
    "compiled_ratio",
]

## **6. Repository Maintenance / Freshness**

**의미**

“현재도 유지되고 있는가”

**핵심 질문**
- maintenance dead 상태인가?
- update/push activity 유지되는가?

In [19]:
maintenance_features = [
    "repo_age_days",
    "last_update_recency_days",
    "last_push_recency_days",
    "update_push_gap_days",
]

## **7. Repository Metadata / Governance**

**의미**

“프로젝트 운영 정책·상태”

**핵심 질문**
- archived 상태인가?
- wiki/discussion 사용하는가?
- governance openness 존재하는가?

In [20]:
governance_features = [
    "repo_size",
    "open_issues_count",
    "has_issues",
    "has_projects",
    "has_downloads",
    "has_wiki",
    "has_pages",
    "has_discussions",
    "archived",
    "disabled",
    "allow_forking",
    "has_pull_requests",
    "issues_per_size",
]